dist: xenial

language: python

sudo: false

branches:
  only:
    - master
    - develop
    - scratch

# Setup databases
services:
  - mongodb  # port 27017 (default)
  - redis-server  # port 6379 (default)

python:
  - 3.6
  - 3.7
  - 3.8

# Install packages
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=scipy -r requirements.txt
  - pip install coveralls
  - pip freeze

# Run tests
script: coverage run --source=pyphi -m py.test --slow

after_success: coveralls

notifications:
  email: false
  slack:
    rooms:
         secure: "C6PSvK/FEmyD+S71VVzS29NZpD9CFI/f3UMjc6i08xYHjFNMZUplfHyUqNLNqgVVBsKR1En4B8ryuriEnM8wwZzCVdxjh7HDsx8aNE2z1XG5tkqoRP4ppNfqNaYRoMcSZFW89DfVNbIVDM11wKXL7/YnRCmlJy0p1NtKzlncXCM="
    on_success: never
    on_failure: always
