[tool.black]
# NOTE: you have to use single-quoted strings in TOML for regular expressions.
# It's the equivalent of r-strings in Python.  Multiline strings are treated as
# verbose regular expressions by Black.  Use [ ] to denote a significant space
# character.
line-length = 88
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git
    | \.tox
    | build
    | dist
    | benchmarks
    | docs\/_themes
  )/
  | pyphi\/examples\.py
)
'''

[tool.isort]
skip_glob = [
  '.tox/*',
  'docs/_themes/*',
  'build/*',
  'dist/*',
  'benchmarks/*',
]
skip = [
  'pyphi/__init__.py',
]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
indent = '    '
default_section = 'THIRDPARTY'
known_first_party = 'pyphi'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'
